dist: bionic

language: php

php:
  - 7.3

before_script:
  - sudo apt update
  - sudo apt install libreoffice-writer
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/paratest